SURVEY_QUESTION_MAPPER = {
    'Unique Response Number': 'unique_response_number',
    '2. Name of school': '2_school_name',
    '3. Type of school': '3_school_type',
    '3.a. If you selected Other, please specify:' : '3a_other',
    '4. What is your role?': '4_role',
    '4.a. Please confirm you are able to respond to this questionnaire on behalf of your school. If not, pass this on to an appropriate colleague. Please specify your role:' : '4a_other_role',
    '5. Overall, how would you rate your schoolâ€™s arts curriculum offer? (Answers will be anonymised and data will not be linked to individual schools.)' : '5_overall_rating_arts_offer',
    '5.a. Why do you rate your schoolâ€™s arts curriculum as excellent/good?': '5a_why_excellent_good',
    '5.b. Why do you rate your schoolâ€™s arts curriculum as mixed?': '5b_why_mixed',
    '5.c. Why do you rate your schoolâ€™s arts curriculum as poor/very poor?': '5c_why_poor',
    '6. Does your school have a particular commitment(s) to pupil entitlement in the arts? (E.g., every pupil learns a musical instrument, or has the opportunity to go on trips each year.)': '6_pupil_arts_entitlement',
    '6.a. If yes, please tell us more about the commitment(s).' : '6a_pupil_entitlement_details',
    '7. Does your school attract additional funding for arts curriculum or enrichment activity?' : '7_additional_arts_funding',
    '7.a. Where does your school attract funding from? Tick all that apply.': '7a_arts_funding_sources',
    "7.a.i. If you selected Other, please specify your school's other sources of arts funding:": '7ai_other_funding_details',
    '8. Does your school offer any of the following non-curricular arts activities that pupils can participate in? (Tick all that apply.)': '8_non_curricular_arts_activities',
    '8.a. Please describe briefly the year groups or key stages that are involved in these activities, or whether they are open to the whole school.': '8a_year_groups_non_curricular_activities',
    '8.b. Do you invite parents or a wider audience to any of these activities?': '8b_parents_wide_audience',
    '8.c. If you selected Other non-curriculum activities, what does your school provide?' : '8c_other_non_curricular_activities',
    '9. Does your school enter pupils into any competitions, platforms or showcases, whether that is at a local, community, regional or national level? (E.g., for drama, dance, art, film or music.)': '9_competitions_showcases',
    '9.a. What competitions, platforms or showcases has your school entered pupils into?': '9a_competitions_details',
    '10. Does your school actively sign-post opportunities for pupils to develop creative skills and participate in arts opportunities beyond the curriculum?': '10_signposting_beyond_curriculum',
    '10.a. What activities are sign-posted?': '10a_signposted_activities_details',
    '11. Do any of your schoolâ€™s governors work in the arts or creative industries?': '11_governors_creative_industries',
    '12. Does your school have a governor with a dedicated remit for the arts and creative education?': '12_governor_dedicated_arts_remit',
    '13. Does your school have... Tick all that apply': '13_arts_facilities',
    '13.a. If you selected Other, please specify what arts or creative facilities your school has:': '13a_other_arts_facilities_details',
    '13.b. What production facilities does your hall or theatre have?': '13b_production_facilities',
    '13.c. Do pupils have access to any of these facilities outside of formal extra-curricular activities and lessons unsupervised?': '13c_unsupervised_access_facilities',
    '13.c.i. If there is a mixed level of access to different facilities, please comment on this here:': '13ci_mixed_access_details',
    '14. How would you rate your schoolâ€™s extra-curricular and arts enrichment offer? (Answers will be anonymised and data will not be linked to individual schools.)': '14_rating_extra_curricular_arts_enrichment_offering',
    '14.a. Why do you rate your schoolâ€™s extra-curricular or arts enrichment offer as excellent or good?': '14a_why_excellent_good',
    '14.b. Why do you rate your schoolâ€™s extra-curricular or arts enrichment offer as mixed?': '14b_why_mixed',
    '14.c. Why do you rate your schoolâ€™s extra-curricular or arts enrichment offer as poor or very poor?': '14c_why_poor',
    '15. Does your school offer any of the following extra-curricular activity or arts enrichment? (Tick all that apply.)' : '15_offer_extracurricular_activity_select',
    '15.a. If you selected Other extra-curricular or arts enrichment activities, please specify:': '15a_other_extracurricular_details',
    '15.b. Do you supply musical instruments?': '15b_supply_musical_instruments',
    '15.c. Are the music lessons (individual or group) run by the school/teachers OR external providers that come into the school? (Tick all that apply.)': '15c_music_lessons_teachers_or_external',
    '15.d. Are the orchestras, ensembles or bands run by the school/teachers OR external providers that come into the school? (Tick all that apply.)': '15d_orchestras_teachers_or_external'
}